version: '3.8'

services:
  mongo:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data  # For CSV/JSON import
    environment:
      MONGO_INITDB_DATABASE: twitter
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/twitter
    

  frontend:
    image: nginx:alpine
    ports:
      - "8008:8008"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mongodb_data: